sky:
  alioss:
    access-key-id: LTAI5t6PdSdkWcdEnWJMSBKX
    access-key-secret: 2u4RX2QOirLnAyjyAwG1x78g6Hj6Mg
    bucket-name: learning-demo-bucket
    endpoint: oss-cn-shanghai.aliyuncs.com

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 159248
  redis:
    host: 127.0.0.1
    port: 6379
    password: 159248
    database: 2
  wechat:
    appid: wx7d62c9753af9dcf8
    secret: b749d3baf7b337ff6442dc4f9c90a1f8




